//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Contacts.Data.SqlServer.Entities
{
    public partial class ContactManagerEntities : ObjectContext
    {
        public const string ConnectionString = "name=ContactManagerEntities";
        public const string ContainerName = "ContactManagerEntities";
    
        #region Constructors
    
        public ContactManagerEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ContactManagerEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ContactManagerEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Contact> Contacts
        {
            get { return _contacts  ?? (_contacts = CreateObjectSet<Contact>("Contacts")); }
        }
        private ObjectSet<Contact> _contacts;

        #endregion
    }
}
